# Generated by Django 4.1.7 on 2023-02-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0002_cause_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('People', 'People'), ('Health', 'Health')], default='People', max_length=10),
            preserve_default=False,
        ),
    ]
