# Generated by Django 4.1.7 on 2023-02-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0004_alter_cause_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='price',
            new_name='initial_price',
        ),
        migrations.AddField(
            model_name='cause',
            name='slid',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cause',
            name='target_price',
            field=models.PositiveIntegerField(default=4000),
            preserve_default=False,
        ),
    ]
