# Generated by Django 4.2.5 on 2024-08-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0004_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='subject',
        ),
    ]
