# Generated by Django 4.1.7 on 2023-02-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0005_rename_price_cause_initial_price_cause_slid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='slid',
        ),
    ]
