# Generated by Django 4.2.5 on 2025-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='image3',
        ),
    ]
