# Generated by Django 4.1.7 on 2023-02-23 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingcause',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
