# Generated by Django 4.1.7 on 2023-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0008_upcomingcause_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingcause',
            name='cause',
        ),
        migrations.AddField(
            model_name='upcomingcause',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('People', 'People'), ('Health', 'Health')], default='good cause', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingcause',
            name='description',
            field=models.TextField(default='good cause'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingcause',
            name='image',
            field=models.ImageField(default='media/causes1.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='upcomingcause',
            name='initial_price',
            field=models.PositiveIntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingcause',
            name='name',
            field=models.CharField(default='upcoming cause', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingcause',
            name='target_price',
            field=models.PositiveIntegerField(default=9000),
            preserve_default=False,
        ),
    ]
