# Generated by Django 4.1.7 on 2023-02-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0009_remove_upcomingcause_cause_upcomingcause_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingcause',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
