# Generated by Django 4.1.7 on 2023-02-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0011_alter_upcomingcause_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='location',
            field=models.CharField(default='zamfara', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingcause',
            name='location',
            field=models.CharField(default='zamfara', max_length=50),
            preserve_default=False,
        ),
    ]
