# Generated by Django 4.1.7 on 2023-02-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0012_cause_location_upcomingcause_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='image',
        ),
    ]
