# Generated by Django 4.1.7 on 2023-02-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0013_remove_cause_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingcause',
            name='image',
        ),
        migrations.AddField(
            model_name='cause',
            name='image',
            field=models.ImageField(default='media/causes1.jpg', upload_to='media'),
        ),
    ]
