# Generated by Django 4.1.7 on 2023-02-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0014_remove_upcomingcause_image_cause_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='cause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pass.upcomingcause'),
        ),
        migrations.AddField(
            model_name='cause',
            name='slug',
            field=models.SlugField(default='cause'),
        ),
        migrations.AddField(
            model_name='upcomingcause',
            name='slug',
            field=models.SlugField(default='cause'),
        ),
    ]
