# Generated by Django 4.1.7 on 2023-02-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0015_cause_cause_cause_slug_upcomingcause_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pass.upcomingcause'),
        ),
    ]
