# Generated by Django 4.1.7 on 2023-02-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0017_cause_image2_cause_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='cause',
        ),
        migrations.CreateModel(
            name='RecentCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pass.upcomingcause')),
            ],
        ),
    ]
