# Generated by Django 4.1.7 on 2023-02-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0018_remove_cause_cause_recentcause'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentcause',
            name='image',
            field=models.ImageField(default='media/causes1.jpg', upload_to='media'),
        ),
    ]
