# Generated by Django 4.1.7 on 2023-02-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0020_alter_recentcause_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='total_price',
            field=models.PositiveIntegerField(default=19999),
            preserve_default=False,
        ),
    ]
