# Generated by Django 4.1.7 on 2023-02-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0021_cause_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='skill_bar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
