# Generated by Django 4.1.7 on 2023-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0022_cause_skill_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='skill_bar',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cause',
            name='total_price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
