# Generated by Django 4.1.7 on 2023-02-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0023_alter_cause_skill_bar_alter_cause_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='skill_bar',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cause',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='cause',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
