# Generated by Django 4.1.7 on 2023-02-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0024_alter_cause_skill_bar_alter_cause_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='skill_bar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
