# Generated by Django 4.1.7 on 2023-02-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0026_alter_cause_skill_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='skill_bar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
