# Generated by Django 4.1.7 on 2023-02-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0028_event_cause_date_delete_recentcause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='skill_bar',
        ),
    ]
