# Generated by Django 4.1.7 on 2023-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0029_remove_cause_skill_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
