# Generated by Django 4.1.7 on 2023-02-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0031_alter_cause_options_alter_cause_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cause',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='cause',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
