# Generated by Django 4.1.7 on 2023-03-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pass', '0033_event_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Member',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pass.member'),
            preserve_default=False,
        ),
    ]
