# Generated by Django 4.1.7 on 2023-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0034_rename_profile_member_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(default='causes1.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image2',
            field=models.ImageField(blank=True, default='causes2.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image3',
            field=models.ImageField(blank=True, default='causes3.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
