# Generated by Django 4.1.7 on 2023-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0038_remove_cause_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='category',
            field=models.CharField(choices=[('Sanitary Measures, Food & Shelter', 'Sanitary Measures, Food & Shelter'), ('Art, Cultural & Arrchitectural Conservation', 'Art, Cultural & Arrchitectural Conservation'), ('Creativity & Empowerment', 'Creativity & Empowerment')], max_length=50),
        ),
    ]
