# Generated by Django 4.1.7 on 2023-03-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0039_alter_cause_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
