# Generated by Django 4.1.7 on 2023-07-26 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pass', '0039_alter_cause_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
      
    ]
