# Generated by Django 4.1.7 on 2023-03-04 19:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0040_alter_cause_image_alter_cause_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 401], upload_to='media'),
        ),
    ]
