# Generated by Django 4.1.7 on 2023-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0044_alter_cause_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
