# Generated by Django 4.1.7 on 2023-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0045_remove_member_user_alter_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(default='CEO', max_length=70),
            preserve_default=False,
        ),
    ]
